### ISSUE TITLE
use claim tip with 0.30 for tipping

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/web-daemon#9]
Starting in 0.30 (currently on 0.21), tipping will need to be done via the claim_tip API call: https://github.com/lbryio/lbry/blob/6feae93c58d83807e133fbe4c62fd3ce904b3400/lbrynet/daemon/Daemon.py#L2392

**Comment by NetOperatorWibby** [comment]
> Invalid value for 'amount':
>
> Decimal inputs require a value in the ones place and in the tenths place
separated by a period. The value provided, '0.001', is not of the correct
format.
>
> The following are examples of valid decimal inputs:
>
> 1.0
> 0.001
> 2.34500
> 4534.4
> 2323434.0000

Here is what I'm sending:

```js
    body: {
      method: data.method,
      params: {
        amount: "0.001",
        claim_id: data.claim_id
      }
    }
```

**Comment by NetOperatorWibby** [comment]
The body is being sent as JSON. I wonder if this is the problem.

**Comment by lyoshenka** [comment]
pinging @eukreign

**Comment by eukreign** [comment]
Amount looks correct. Maybe you have something that's converting it to a float before it's sent? Would be good to see the raw JSON in the HTTP request you're making.

**Comment by NetOperatorWibby** [comment]
False alarm. I realized I was still calling `wallet_send` instead of `claim_tip`.
